desc "Update App Store page (metadata + screenshots + preview video)"
lane :store_page do

  app_store_connect_api_key(
    key_id: "34V5LQAYUR",
    issuer_id: "dded258b-e67d-4977-b7c0-1035d0747872",
    key_filepath: "fastlane/api_key/AuthKey_34V5LQAYUR.p8",
    duration: 1200,
    in_house: false
  )

  deliver(
    app_identifier: "com.spotolcom.melkalk",

    # НЕ грузим билд
    skip_binary_upload: true,

    # ГРУЗИМ ВСЁ ОСТАЛЬНОЕ
    skip_metadata: false,
    skip_screenshots: false,

    # ВАЖНО ↓ (без этого видео не загрузится)
    overwrite_screenshots: true,

    force: true,
    submit_for_review: false,
    automatic_release: false,
    run_precheck_before_submit: false
  )
end


